disabled_rules:
- trailing_whitespace
- identifier_name
- redundant_string_enum_value
- type_name
- function_parameter_count
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Pods
